### ISSUE TITLE
Message TX - JSON

### ISSUE THREAD

**Issue by vrontis** [Qoracoin/Qora#16]
JSON returns true while is false
```"encrypted":"true" ```

Example : http://127.0.0.1:9085/transactions/signature/5EstiTm1ShdJFr9Pur3VgsHZAZyn3KkBvjvFe8UPcfRsNzAupUhFZdkcysguzthYTxUPxk5iQTh6WXJC2z29vCi4

JSON : 
```{"reference":"uTsMrTr19GSPwWYyb9FpkntQKcS6jSAXuBf2ykYhVuA6Ag6LeTYVyTnbFTtfZM29wHr8NCv3Ej6HSYcCsrs5AQt","creator":"QUWxrwJ8AqKkz4B2b1aMc9aD83WPRcLxss","amount":1.00000000,"data":"54ubkpURFFrJc8","encrypted":"true","signature":"5EstiTm1ShdJFr9Pur3VgsHZAZyn3KkBvjvFe8UPcfRsNzAupUhFZdkcysguzthYTxUPxk5iQTh6WXJC2z29vCi4","fee":"1.00000000","recipient":"QQQ7GvQPJbLRJrD8E2EnZb22RzBSuf3hgY","type":17,"confirmations":5,"isText":"true","timestamp":1431969158248}```

**Comment by agran** [comment]
/Qora/src/qora/transaction/MessageTransaction.java
	public boolean isEncrypted()
	{		
		return (Arrays.equals(this.encrypted,new byte[1]))?true:false;
	}
	
	//this.encrypted == 0
	
	//return = true



=============
new byte[1]    always =  0

There error

**Comment by xloem** [comment]
This issue is resolved, should be closed.  true:false were reversed so that false is returned if encrypted == "\0"
