### ISSUE TITLE
Check for confirmation before closing

### ISSUE THREAD

**Issue by xloem** [Qoracoin/Qora#20]
My client seems to be randomly receiving WINDOW_CLOSING events and shutting down.

I don't know why it's getting these events, but I would like for it to stay open!

**Comment by Skerberus** [comment]
Does this even happen if you use the lightwallet?

**Comment by xloem** [comment]
It has only happened a couple times over the past week.  It's hard to test with the lightwallet because it's hard to use the lightwallet to check my messages, transfer funds, or unlock the wallet, is there a web UI for these activities?

**Comment by Skerberus** [comment]
The lightwallet has a tray icon ( if your OS supports this), click on that and you should get every panel you need to unlock, message, transfer funds and so on.

**Comment by xloem** [comment]
I'll switch and keep testing.

**Comment by xloem** [comment]
Looks like it doesn't happen with lightwallet.  I guess this was probably #21 .
