### ISSUE TITLE
Feature Request: More pebble apis

### ISSUE THREAD

**Issue by xloem** [Qoracoin/Qora#22]
It would be great if the interactive website feature had functionality comparable to most of the json apis.  Maybe this could even  be done by directly exposing API classes such as TransactionsResource or BlocksResource.

I imagine being able to make a site which procedurally generates content from the blockchain or can initiate actions such as blog posts or message sends.

**Comment by Skerberus** [comment]
Pebble is a templating engine that can help enhance the content of websites. So it can help display dynamic content from the blockchain, it can not directly be used change the blockchain (e.g. create blogposts, send transactions, messages, modify namestorage). Calling the API and therefore changing the blockchain is already possible with javascript, you can see examples here : http://qora.co.in:9090/registername or http://qora.co.in:9090/webwallet these are websites that are completly part of the blockchain, they use pebble to inject some content and javascript to create API calls for registering names or making payments (just look at the source). You can also examine the source here http://qora.co.in:9090/namestorage:webwallet
Is that something you are looking for? Feel free to ask more questions :).

**Comment by xloem** [comment]
I see!  The api is accessible on port 80 by posting to /index/api.html , so it can be used via ajax.  Thanks.
I agree mutating calls should be done this way, not in pebble.
