### ISSUE TITLE
If during synchronization wallet, the network has a new block, the error occurs.

### ISSUE THREAD

**Issue by agran** [Qoracoin/Qora#27]
If during synchronization wallet, the network has a new block, the error occurs.

**Comment by icreator** [comment]
may be block form net not converted from bytes

**Comment by icreator** [comment]
public static Transaction Parse(byte[] data) throws Exception{

**Comment by catbref** [comment]
Closing this in favour of issue #65 which looks like it could be similar and also contains logfile dumps.
