### ISSUE TITLE
NullPointerException when launching Qora on Ubuntu

### ISSUE THREAD

**Issue by eshriek** [Qoracoin/Qora#60]
> `2016-09-03 08:34:48 ERROR DBMap:182 - 
> java.lang.NullPointerException
>   at qora.transaction.DeployATTransaction.getATaccount(DeployATTransaction.java:512)
>   at qora.transaction.DeployATTransaction.getRecipientAccounts(DeployATTransaction.java:571)
>   at database.TransactionFinalMap$2.run(TransactionFinalMap.java:93)
>   at database.TransactionFinalMap$2.run(TransactionFinalMap.java:1)
>   at org.mapdb.Bind$6.update(Bind.java:438)
>   at org.mapdb.BTreeMap.notify(BTreeMap.java:2792)
>   at org.mapdb.BTreeMap.put2(BTreeMap.java:755)
>   at org.mapdb.BTreeMap.put(BTreeMap.java:643)
>   at database.DBMap.set(DBMap.java:141)
>   at database.TransactionFinalMap.add(TransactionFinalMap.java:181)
>   at qora.block.Block.process(Block.java:762)
>   at qora.block.Block.process(Block.java:705)
>   at qora.Synchronizer.process(Synchronizer.java:343)
>   at qora.Synchronizer.synchronize(Synchronizer.java:195)
>   at controller.Controller.update(Controller.java:1024)
>   at qora.BlockGenerator.run(BlockGenerator.java:178)`

Tried replacing 'data' and 'dataBak' folders with https://cloud.crowetic.com/s/IDzrYBiqXnhNCvg which did not resolve the problem.
Currently downloading entire chain...

**Comment by catbref** [comment]
Closed as fixed thanks to commit 9760b75
