### ISSUE TITLE
wallet use question

### ISSUE THREAD

**Issue by jdcer** [Qoracoin/Qora#82]
why i cant open the Qora.exe,and i can only use the Qora.jar.

**Comment by LouisWayne** [comment]
This project is dead

**Comment by catbref** [comment]
Are you using the latest v0.26.4?
When you try to open Qora.exe are you doing it via desktop icon/start menu?
Do you see any error messages?
Is there anything mentioned in the log files which you can find in %APPDATA%\Roaming\Qora\

Going to need more details please!

**Comment by LouisWayne** [comment]
@catbref are you a developder? Why is the website dead?

**Comment by crowetic** [comment]
@LouisWayne - The website is down on purpose right now, as we're rebuilding everything from the gound up. First we will make everything stable, THEN we will promote it again. Now we are in the first step of this. Making the wallet stable is more important than the website at the moment.
