### ISSUE TITLE
Support mounted data directory (and dataBak/wallet dirs)

### ISSUE THREAD

**Issue by notsoshifty** [Qoracoin/Qora#86]
If the data directory ($QORA_HOME/data) is mounted from another location, and is either empty or needs to be erased by Qora during startup (e.g. due to corruption issues), Qora fails to start. This is probably because the data directory can't be deleted (due to being mounted).

You can replicate this issue using bind mounts:

```
cd $QORA_HOME
rm -rf data dataBak
mkdir data
mkdir -p ~/deleteme/data
mount --bind ~/deleteme/data data
./run.sh
```

Changing the behavior to delete everything under the data directory, but not the data directory itself, would allow mounted directories to be used.

This might also happen with the wallet and dataBak directories; I haven't tested this.

**Comment by catbref** [comment]
Should be sorted in new v0.26.6 - please report back so I can close this issue.

**Comment by catbref** [comment]
Can I get a confirmation from OP that this works in docker context?

**Comment by notsoshifty** [comment]
Works perfectly - thanks.
