### ISSUE TITLE
Support headless mode

### ISSUE THREAD

**Issue by notsoshifty** [Qoracoin/Qora#87]
Qora doesn't currently support starting in headless mode. Such support would likely be a pre-requisite for exchanges to use Qora.

**Comment by catbref** [comment]
Should be fixed in new v0.26.6 - please install and report back so I can close issue

**Comment by askmeboy** [comment]
Thanks cat ,

**Comment by catbref** [comment]
Can I get a confirmation from OP that this works in docker context?

**Comment by notsoshifty** [comment]
Works perfectly - thanks.
